import os

env_test = Environment()

Import('models_lib')

boost_prefix = "/usr"
libs = [ 'boost_unit_test_framework', models_lib ]

sources = [ "coordinate-test.cpp", "IEEE802154-test.cpp" ]
env_test.Append(CPPPATH = [os.path.join(boost_prefix, "include")])
env_test.Append(CPPPATH= "../models")
env_test.Append(LIBPATH = [os.path.join(boost_prefix, "lib")])
app = env_test.Program(source = "coordinate-test.cpp", LIBS = libs, LIBPATH = [ "../models" ])
app2 = env_test.Program(source = "IEEE802154-test.cpp", LIBS = libs, LIBPATH = [ "../models" ])
env_test.Default([app, app2])

