Import('env')
local_env = env.Clone()

Import('models_lib')
Import('network_lib')

libs = [ models_lib, network_lib ]

core_lib = local_env.StaticLibrary("core", Split("simulation.cpp"), CPPPATH=["..", "."], LIBS= libs + ["pthread", "boost_system-mt"])
Export('core_lib')
