import os

Object("coordinate.cpp")
Object("pathlossmodel.cpp")
Object("node.cpp")
Object("IEEE802154.cpp")

env_boost = Environment()
boost_prefix = "/usr"
libs = [ ]

sources = [ "test-suite.cpp", "IEEE802154.cpp" ]
env_boost.Append(CPPPATH = [os.path.join(boost_prefix, "include")])
env_boost.Append(LIBPATH = [os.path.join(boost_prefix, "lib")])
app = env_boost.Program(target = "test-suite", source = sources, LIBS = libs)
env_boost.Default(app)

