import os

Import('env')
local_env = env.Clone()

models_lib = StaticLibrary("models",
                           Split("coordinate.cpp pathlossmodel.cpp modulation.cpp IEEE802154.cpp"),
                           CPPPATH = [ "..", "."])
Export('models_lib')

local_env = Environment()
boost_prefix = "/usr"

sources = [ "test-suite.cpp" ]
local_env.Append(CPPPATH = [os.path.join(boost_prefix, "include")])
local_env.Append(LIBPATH = [os.path.join(boost_prefix, "lib")])
app = local_env.Program(target = "test-suite",
                        source = sources,
                        LIBS = models_lib)
local_env.Default(app)

